#ifndef VALUE_DEFINITIONS_H
#define VALUE_DEFINITIONS_H

#define LANE_LEFT 0
#define LANE_RIGHT 1
#define LANE_UNDEFINED 2
#define LANE_LEFT_SIDE 3
#define LANE_RIGHT_SIDE 4

#define SIGN_GIVE_WAY 13
#define SIGN_STOP 14
#define SIGN_YIELD_ONCOMING_TRAFFIC 100
#define SIGN_TURN_LEFT 34
#define SIGN_TURN_RIGHT 33
#define SIGN_SPEED_ZONE_10 112
#define SIGN_SPEED_ZONE_20 0
#define SIGN_SPEED_ZONE_30 1
#define SIGN_SPEED_ZONE_40 113
#define SIGN_SPEED_ZONE_50 2
#define SIGN_SPEED_ZONE_60 3
#define SIGN_SPEED_ZONE_70 4
#define SIGN_SPEED_ZONE_80 5
#define SIGN_SPEED_ZONE_90 114
#define SIGN_SPEED_ZONE_END 101
#define SIGN_NO_PASSING_ZONE 9
#define SIGN_NO_PASSING_ZONE_END 41
#define SIGN_PASS_BY_ON_RIGHT 38 //Currently unused
#define SIGN_PASS_BY_ON_LEFT 39 //Currently unused
#define SIGN_PRIORITY_ROAD 12
#define SIGN_CROSSWALK 102
#define SIGN_SHARP_TURN_LEFT 103
#define SIGN_VERY_SHARP_TURN_LEFT 104
#define SIGN_SHARP_TURN_RIGHT 105
#define SIGN_VERY_SHARP_TURN_RIGHT 106
#define SIGN_STEEP_DECLINE 107
#define SIGN_STEEP_INCLINE 108
#define SIGN_PARKING 109
#define SIGN_EXPRESSWAY_BEGIN 110
#define SIGN_EXPRESSWAY_END 111
#define PEDESTRIAN 115

#define MARKING_BARRED_AREA_LEFT 200
#define MARKING_BARRED_AREA_RIGHT 201
#define MARKING_CROSSWALK 202
#define MARKING_INTERSECTION 203
#define MARKING_START_LINE 204
#define MARKING_ARROW_RIGHT 205
#define MARKING_ARROW_LEFT 206
#define MARKING_CROSSING_STOP 207
#define MARKING_CROSSING_YIELD 208
#define MARKING_PARKING_SPOT_BLOCKED 209

#endif